version: "3.7"
services:
    dev_cli:
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - type: bind
          source: .
          target: /usr/local/dev
          consistency: cached
        - type: bind
          source: ${HOME}/.gitconfig
          target: /usr/local/dev/.gitconfig
          consistency: cached
        - type: bind
          source: ${HOME}/.ssh
          target: /usr/local/dev/.ssh
          consistency: cached